// ─────────────────────────────────────────────────────────────────────────────
// BatchNexus — Ops Copilot dynamic prompt chips, keyed by current page.
// Context (page, role) is used in logic only — never shown as visible chips.
// ─────────────────────────────────────────────────────────────────────────────

export const PROMPTS_BY_PAGE: Record<string, string[]> = {
  "/": [
    "Any cold-chain alerts today?",
    "What needs attention right now?",
    "Summarize today's operations",
    "Which lots are blocked?",
    "Which lots need priority dispatch?",
  ],
  "/inbound": [
    "What fields need review?",
    "Is this receipt ready for QC?",
    "Show supplier history",
    "What is missing from this intake?",
  ],
  "/qc": [
    "Explain the AI QC score",
    "What should I review before approval?",
    "What happens if I approve?",
    "Why is this marked for review?",
    "Show related lot history",
  ],
  "/ppic": [
    "Which lots are ready for production?",
    "What should be prioritized next?",
    "Show blocked production inputs",
    "Which released lots are still unassigned?",
  ],
  "/lots": [
    "Where is this lot?",
    "Show full timeline",
    "Which samples used this lot?",
    "Who approved this lot?",
    "Open related audit trail",
  ],
  "/warehouse": [
    "Why is this slot recommended?",
    "Why is COLD-B blocked?",
    "Assign to recommended slot",
    "Any cold-chain alerts here?",
    "Show warehouse policy rules",
  ],
  "/dispatch": [
    "What's blocking dispatches?",
    "Which samples are pending dispatch?",
    "Which lot is linked to this shipment?",
    "What needs urgent dispatch today?",
  ],
  "/audit": [
    "Explain the integrity hash",
    "Show QC approval events",
    "Show warehouse movement logs",
    "Export compliance report",
    "Which actions were generated by Ops Copilot?",
  ],
  "/summary": [
    "Summarize today's operations",
    "Any cold-chain alerts today?",
    "What needs attention right now?",
  ],
  "/policy": [
    "Why is COLD-B blocked?",
    "Explain how slots are chosen",
    "Show current policy rules",
  ],
};

const DEFAULT_PROMPTS = [
  "Any cold-chain alerts today?",
  "Which lots are blocked?",
  "What needs attention right now?",
  "Where is LOT-2026-051?",
];

/** Returns the suggested prompt chips for the given base route. */
export function getPromptsForPage(page: string): string[] {
  const base = "/" + (page.split("/")[1] || "");
  return PROMPTS_BY_PAGE[base] || PROMPTS_BY_PAGE[page] || DEFAULT_PROMPTS;
}

/** Friendly label for the current page — used in audit logs, not displayed in UI. */
export const PAGE_LABELS: Record<string, string> = {
  "/": "Dashboard",
  "/inbound": "Inbound Intake",
  "/qc": "QC Release",
  "/ppic": "PPIC Board",
  "/lots": "Lot Traceability",
  "/warehouse": "Warehouse",
  "/dispatch": "Dispatch",
  "/copilot": "Ops Copilot",
  "/summary": "Daily Summary",
  "/policy": "Policy Rules",
  "/audit": "Audit Log",
};

export function getPageLabel(page: string): string {
  const base = "/" + (page.split("/")[1] || "");
  return PAGE_LABELS[base] || PAGE_LABELS[page] || "BatchNexus";
}
